# Generated by Django 3.0.8 on 2020-08-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200828_1259'),
        ('Users', '0003_auto_20200828_2110'),
    ]

    operations = [
    ]
