# Generated by Django 3.0.8 on 2020-08-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_merge_20200828_1309'),
        ('Users', '0003_auto_20200828_2134'),
    ]

    operations = [
    ]
