# Generated by Django 3.1 on 2020-08-28 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('writingDate', models.DateField(default=datetime.date.today)),
                ('novelImage', models.ImageField(upload_to='novel/')),
                ('novelPrice', models.IntegerField(default=0, null=True)),
                ('novelContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=15)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='Books.novel')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('bookCategory', models.CharField(choices=[('세계문학전집', '세계문학전집'), ('인문', '인문'), ('철학', '철학'), ('종교', '종교'), ('사회', '사회'), ('에세이', '에세이'), ('과학', '과학'), ('역사', '역사'), ('경제경영', '경제경영'), ('자기계발', '자기계발'), ('여행', '여행'), ('라이프스타일', '라이프스타일'), ('부모', '부모'), ('어린이와청소년', '어린이와청소년'), ('판타지와무협', '판타지와무협'), ('로맨스', '로맨스'), ('만화', '만화'), ('애니메이션', '애니메이션')], default='', max_length=50)),
                ('editDate', models.DateField()),
                ('bookImage', models.ImageField(upload_to='book/')),
                ('bookPrice', models.IntegerField(default=0, null=True)),
                ('contents', models.ManyToManyField(to='Books.Novel')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
