# Generated by Django 3.0.8 on 2020-08-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('writingDate', models.DateField()),
                ('novelImage', models.ImageField(upload_to='novel/')),
                ('novelPrice', models.IntegerField(default=0, null=True)),
                ('novelContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('editDate', models.DateField()),
                ('bookImage', models.ImageField(upload_to='book')),
                ('bookPrice', models.IntegerField(default=0, null=True)),
                ('contents', models.ManyToManyField(to='Books.Novel')),
            ],
        ),
    ]
