# Generated by Django 3.0.8 on 2020-08-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_novel_like'),
        ('Books', '0002_novel_novelcategory'),
    ]

    operations = [
    ]
