# Generated by Django 3.0.8 on 2020-08-28 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Books', '0003_merge_20200828_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='novel_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='novel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
