# Generated by Django 3.0.8 on 2020-08-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_bookcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookCategory',
            field=models.CharField(choices=[('세계문학전집', '세계문학전집'), ('인문', '인문'), ('철학', '철학'), ('종교', '종교'), ('사회', '사회'), ('에세이', '에세이'), ('과학', '과학'), ('역사', '역사'), ('경제경영', '경제경영'), ('자기계발', '자기계발'), ('여행', '여행'), ('라이프스타일', '라이프스타일'), ('부모', '부모'), ('어린이/청소년', '어린이/청소년'), ('판타지/무협', '판타지/무협'), ('로맨스', '로맨스'), ('만화', '만화'), ('애니메이션', '애니메이션')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='novel',
            name='novelCategory',
            field=models.CharField(choices=[('세계문학전집', '세계문학전집'), ('인문', '인문'), ('철학', '철학'), ('종교', '종교'), ('사회', '사회'), ('에세이', '에세이'), ('과학', '과학'), ('역사', '역사'), ('경제경영', '경제경영'), ('자기계발', '자기계발'), ('여행', '여행'), ('라이프스타일', '라이프스타일'), ('부모', '부모'), ('어린이/청소년', '어린이/청소년'), ('판타지/무협', '판타지/무협'), ('로맨스', '로맨스'), ('만화', '만화'), ('애니메이션', '애니메이션')], default='', max_length=50),
        ),
    ]
