# Generated by Django 3.0.8 on 2020-08-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20200825_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='novelTag',
            new_name='tags',
        ),
    ]
