# Generated by Django 3.0.8 on 2020-08-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_auto_20200825_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='tags',
            new_name='Noveltags',
        ),
    ]
