# Generated by Django 3.0.8 on 2020-08-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_auto_20200826_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
    ]
