# Generated by Django 3.0.8 on 2020-08-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_editor'),
        ('Books', '0010_auto_20200827_0558'),
        ('Books', '0003_auto_20200819_0051'),
    ]

    operations = [
    ]
